import os
import logging
import google.generativeai as genai

logger = logging.getLogger(__name__)


class PlaywrightCodeGenerator:
    """
    Generate Playwright Python code from HTML using Gemini LLM
    """
    
    def __init__(self):
        api_key = os.getenv('GEMINI_API_KEY')
        genai.configure(api_key=api_key)
        # Use gemini-pro (free tier, stable model)
        self.model = genai.GenerativeModel('gemini-2.5-flash')
    
    def generate_page_object(self, html_content: str, url: str) -> str:
        """
        Generate Python Playwright Page Object code from HTML
        
        Args:
            html_content: HTML content of the page
            url: URL of the page
            
        Returns:
            Python code as string
        """
        try:
            logger.info(f"Generating Playwright code for URL: {url}")
            
            # Truncate HTML if too long (to avoid token limits)
            max_html_length = 10000
            if len(html_content) > max_html_length:
                html_content = html_content[:max_html_length] + "\n... (truncated)"
            
            prompt = f"""Tôi có đoạn HTML này:

```html
{html_content}
```

Hãy tạo file Python sử dụng Playwright (sync API) cho trang web này theo Page Object Model.

Yêu cầu bắt buộc:
1. Tạo class Page Object Model (POM) đúng chuẩn
2. Đặt tên class, biến, method theo PEP8 (snake_case)
3. Ưu tiên dùng CSS selector ngắn gọn, ổn định (tránh XPath phức tạp)
4. Khai báo rõ các locator cho các element quan trọng của page (links, buttons, headings, articles nếu có)
5. Tạo các method để:
   - navigate tới page
   - đợi page load hoàn tất
   - lấy dữ liệu chính (ví dụ: title, danh sách bài viết, heading chính)
6. Import đầy đủ: from playwright.sync_api import sync_playwright, expect
7. BẮT BUỘC có khối:
   if __name__ == "__main__":
   để file có thể chạy trực tiếp trên local bằng lệnh:
   python <filename>.py
8. Trong hàm main:
   - Khởi tạo Playwright với sync_playwright()
   - Mở browser (headless=False)
   - Tạo page
   - Gọi Page Object
   - Thực hiện các hành động cơ bản
   - In ra kết quả cần thiết (ví dụ: page title)
9. LƯU Ý QUAN TRỌNG về assertions:
   - CHỈ dùng expect() cho Page hoặc Locator objects
   - VÍ DỤ ĐÚNG: expect(page).to_have_url(url)
   - VÍ DỤ ĐÚNG: expect(page_object.heading_locator).to_be_visible()
   - KHÔNG BAO GIỜ dùng: expect(string_variable) - SẼ BỊ LỖI!
   - Để kiểm tra string/number, dùng assert: assert len(title) > 0, "Title is empty"
   - Để kiểm tra contains: assert "keyword" in title, "Title missing keyword"
10. Các expectation PHÙ HỢP với page:
   - expect(page).to_have_url(url) - verify URL
   - expect(locator).to_be_visible() - verify element visible
   - assert len(text) > 0 - verify string not empty
   - assert count >= 1 - verify có ít nhất 1 item
11. Không sử dụng pytest
12. Không giải thích gì thêm

Chỉ trả về DUY NHẤT code Python hoàn chỉnh có thể chạy trực tiếp."""

            # Generate with Gemini
            response = self.model.generate_content(prompt)
            code = response.text
            
            # Clean up code markers if present
            if code.startswith("```python"):
                code = code.replace("```python", "").replace("```", "").strip()
            elif code.startswith("```"):
                code = code.replace("```", "").strip()
            
            logger.info(f"Successfully generated Playwright code for {url}")
            return code
            
        except Exception as e:
            logger.error(f"Error generating Playwright code: {str(e)}", exc_info=True)
            # Return a basic template on error
            return self._get_fallback_template(url)
    
    def _get_fallback_template(self, url: str) -> str:
        """
        Return a basic template if LLM generation fails
        """
        class_name = "PageObject"
        
        return f'''"""
Page Object Model for {url}
Generated by SEO Tech Platform
"""

from playwright.sync_api import Page, expect


class {class_name}:
    """
    Page Object for {url}
    """
    
    def __init__(self, page: Page):
        """Initialize the page object"""
        self.page = page
        self.url = "{url}"
    
    def navigate(self):
        """Navigate to the page"""
        self.page.goto(self.url)
    
    def get_title(self) -> str:
        """Get page title"""
        return self.page.title()
    
    def wait_for_load(self):
        """Wait for page to load"""
        self.page.wait_for_load_state("networkidle")
'''
